name: compile-qt6.4.0-plugin
run-name: ${{ github.actor }} Build and Release Compass plugin (Linux + Qt 6.4.0)
on: 
  push:
    paths:
      - 'compass/compass.*'
      - '.github/workflows/compile-qt6.4.0-plugin.*'
jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            version: '6.4.0'
            host: 'linux'
            target: 'desktop'
            dir: '${{ github.workspace }}/'
      - name: Build #1
        run: qmake Compass.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
      - name: Build #2
        run: make -f Makefile qmake_all
      - name: Build #3
        run: make -j8
      - name: Archive plugin
        uses: actions/upload-artifact@v3
        with:
          name: qt6-plugin
          path: |
              libcompassplugin.so
              README.md
              LICENSE.md
              Changelog.md
              docs/latex/refman.pdf
              compass/compass.h
              compass/compass.cpp
              compass/compass.pri
